name: Trigger AML Job

on:
  push:
    branches:
      - main
 


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: Set Azure ML workspace as default
      run: |
        az configure --defaults group='rg-dev-mlops'
        az configure --defaults workspace='mlw-dev-mlops'
    - name: Create dataset in Azure ML workspace
      run: |
        az ml job create --file src/job.yml
        

